<div class="alert alert-info">
<h1>Count Regression</h1>
<h4>Homework Environmental Statistics 2</h4>
<h4>Your Names in Here!</h4>
</div>

This weeks exercises will practice the content of the lecture and tutorials and *extend* them in different ways:
 - step-wise model selection;
 - BIC as criterion of model quality;
 - plot univariate relationship from a multivariate model (“conditional plot”).
 
*Please* try to **switch off** all automatic reporting of model selection steps or package warnings, which both only swamp the PDF you generate without providing useful information.

## Exercise 1 (20 points): Plant species richness on Galapagos islands 
Galapagos is a very remote archipelago. Its unique fauna and flora have attracted biologists, ecologists and evolutionary biologists for hundreds of years. The data set `gala` (in **faraway**) gives the total and endemic number of plant species for each of the 30 islands of Galapagos, along with some geographic information. What are the key drivers of plant species richness? (Hint: The number of species is typically a [power-law function of area](https://en.wikipedia.org/wiki/Species%E2%80%93area_relationship)   *A*: $S = cA^z$. On a log-log-scale, this becomes $\log S = \log c + z \log A$. Using count data, *we automatically log-transform the response*, so we additionally need to use $\log$ area as predictor.) 


  1. Plot the logarithm of the number of plant species against log(area), elevation and distance to nearest island, separately. (**2 points**)
  2. Formulate a GLM for count data (Poisson), using the above three variables as predictors. Add pairwise interactions and, if the plot suggests a non-linear relationship, also quadratic terms. Is this a "good model" (explained deviance, dispersion, number of predictors, etc.)? (**3 points**)
  3. Repeat the same plotting, analysis and critique for the number of endemic plant species. (**2 points**)
  4. Repeat the species richness analysis using a negative binomial GLM. Does that make a difference to (i) model parameters and their errors, (ii) significances, and (iii) dispersion? (**3 points**)
  5. Repeat step 4 for the *endemic* species richness. (**2 points**)
  6. Simplify both negative binomial models automatically, using backwards stepwise model selection with BIC as criterion. (**3 points**)
  7. Plot both data and the models (with 95% confidence intervals) for the effect of log(area); use the untransformed scale for the response. Make the plot size 5 x 5 inches (not the default 4 x 4). (**3 points**)
  8. Interpret the findings, particular the figure from step 7. Pay attention to whether the power-law slopes ("z" in the above equation) are similar or not. (**2 points**)

In [ ]:
# add other necessary packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression, PoissonRegressor
from sklearn.metrics import mean_squared_error
import pingouin as pg
from patsy import dmatrices
import scipy
from mlxtend.feature_selection import SequentialFeatureSelector

import warnings

In [26]:
# call dataset
gala = pd.read_csv("gala.csv")

# Reset the index by replacing with name
gala = gala.set_index('Name')
gala.describe()

,Species,Endemics,Area,Elevation,Nearest,Scruz,Adjacent
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,85.233333,26.100000,261.708667,368.033333,10.060000,56.976667,261.098333
std,114.633053,27.331111,864.110519,421.604937,14.274636,68.032334,864.518967
min,2.000000,0.000000,0.010000,25.000000,0.200000,0.000000,0.030000
25%,13.000000,7.250000,0.257500,97.750000,0.800000,11.025000,0.520000
50%,42.000000,18.000000,2.590000,192.000000,3.050000,46.650000,2.590000
75%,96.000000,32.250000,59.237500,435.250000,10.025000,81.075000,59.237500
max,444.000000,95.000000,4669.320000,1707.000000,47.400000,290.200000,4669.320000

In [2]:
gala.head(10)

              Species  Endemics   Area  Elevation  Nearest  Scruz  Adjacent
Name
Baltra             58        23  25.09        346      0.6    0.6      1.84
Bartolome          31        21   1.24        109      0.6   26.3    572.33
Caldwell            3         3   0.21        114      2.8   58.7      0.78
Champion           25         9   0.10         46      1.9   47.4      0.18
Coamano             2         1   0.05         77      1.9    1.9    903.82
Daphne.Major       18        11   0.34        119      8.0    8.0      1.84
Daphne.Minor       24         0   0.08         93      6.0   12.0      0.34
Darwin             10         7   2.33        168     34.1  290.2      2.85
Eden                8         4   0.03         71      0.4    0.4     17.95
Enderby             2         2   0.18        112      2.6   50.2      0.10

### 1.1  Plotting

In [2]:
# The plot

### 1.2 Analysis

In [1]:
# fit

In [3]:
# is this a good model?


### 1.3 Endemics

In [4]:
# The plot






# The fit

### 1.4 Negative binomial model for plant species richness

In [5]:
# estimate the what `alpha` value to use

In [6]:
# fit Negative binomial

In [7]:
# is model good?

In [1]:
# dispersion?



### 1.5 Negative binomial model for endemic plant species richness

In [9]:
# what `alpha` value to use?

In [10]:
# Negative binomial fit

In [11]:
# is model good?



### 1.6 Simplify models

In [13]:
# To ignore all warnings
warnings.filterwarnings('ignore')




# Perform stepwise selection with r2 criterion

## Model for Species

In [14]:
# To ignore all warnings
warnings.filterwarnings('ignore')


# Perform stepwise selection with r2 criterion


## Model for Endemics


### 1.7 Plot data and regression lines with confidence intervals
Note: In python, when are ploting against a log-transformed "X", you have to force the x-axis to be log-scaled by adding `plt.xscale('log')` to the plotting code.

In [8]:
# Create the scatter plot

## 1.8 Interpretation